# #ddev-generated
# This file is placed by the justafish/ddev-drupal-core-dev addon.

webimage_extra_packages: ["chromium-driver"]
ddev_version_constraint: '>=v1.23.1'
upload_dirs:
# The install technique tries to remove all of sites/default/files
# but with DDEV + mutagen that isn't possible.
# so just redirect the upload_dirs.
    - .ddev/tmp
additional_hostnames:
 - ${DDEV_SITENAME}-testing.${DDEV_TLD}
web_environment:
    - BROWSERTEST_OUTPUT_DIRECTORY=/var/www/html/web/sites/simpletest/browser_output
    - BROWSERTEST_OUTPUT_BASE_URL=${DDEV_SITENAME}-testing.${DDEV_TLD}
    - SIMPLETEST_BASE_URL=${DDEV_PRIMARY_URL}
    - SIMPLETEST_DB=mysql://root:root@db/phpunit
corepack_enable: true
hooks:
    post-start:
        - exec: mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS phpunit; GRANT ALL ON phpunit.* to 'db'@'%';"
          service: db
