#!/bin/bash

## Description: Clean up test results
## Usage: tests-cleanup
## Example: "ddev tests-cleanup"

TOP_LEVEL="/var/www/html"
cd $TOP_LEVEL

if [ ! -d "web/test_output" ]
then
  echo "The expected folder web/test_output does not exist."
  exit 2
fi

rm web/test_output/*.counter
rm web/test_output/*.html

echo "Test files removed."
